node {
  parameters {
    string(name: "CLUBB_BRANCH", defaultvalue: "origin/master", trim: true, description: "The branch of CLUBB with you're changes to be copied over.")
    choice(name: "TEST", choices: ["cam_scam_gfortran", "cam_global_ERP_Ln9_gfortran_test"], trim: true, description: "Choose which test from CAM you want to run.")
  }
  stage('Clone Repo') {
    checkout scm
  }
  stage('Copy CLUBB Code') {
    sh './jenkins_tests/cam_clubb_code_copy/cam_clubb_code_copy.bash ${CLUBB_BRANCH} ${WORKSPACE}' 
  }
  stage('Load Jenkinsfile') {
    load "jenkins_tests/${TEST}/Jenkinsfile"
  }
}
