pipeline {
  agent any
  stages {
    stage('Check out externals') {
      steps {
        sh 'python manage_externals/checkout_externals -e Externals.cfg'
      }
    }
    stage('Copy Config Files') {
      steps {
        sh '''cp -f cime_config_cesm_machines_files/config_compilers.xml cime/config/cesm/machines/config_compilers.xml
              cp -f cime_config_cesm_machines_files/config_machines.xml cime/config/cesm/machines/config_machines.xml'''
      }
    }
    stage('Make cprnc') {
      steps {
        dir(path: 'cime/tools/cprnc') {
          sh 'bash -c "export LIB_NETCDF=/usr/local/NETCDF-Fortran-4.4.5-gfortran/lib; export INC_NETCDF=/usr/local/NETCDF-Fortran-4.4.5-gfortran/include; ../configure --macros-format=Makefile --mpilib=mpi-serial; source ./.env_mach_specific.sh; make"'
        }

      }
    }
    stage('Run CAM') {
      steps {
        sh '''source /opt/intel/bin/ifortvars.sh intel64
              rm -rf /home/jenkins/cam_output/scratch/ERP_Ln9.f10_f10_mg37.F2000climo.nelson_gnu.cam-outfrq9s.*
              sed -i \'s|clubb_params(iC14) = clubb_c14|clubb_params(iC14) = clubb_c1|\' /home/pub/bitten/tmp/cam/src/physics/cam/clubb_intr.F90
              sed -i \'s|clubb_config_flags%l_stability_correct_tau_zm = clubb_l_stability_correct_tau_zm|clubb_config_flags%l_stability_correct_tau_zm = .false.|\' /home/pub/bitten/tmp/cam/src/physics/cam/clubb_intr.F90
              cime/scripts/create_test ERP_Ln9.f10_f10_mg37.F2000climo.nelson_gnu.cam-outfrq9s'''
      }
    }
  }
  post {
    always {
      script {
      if ( "${env.JOB_NAME}" == "cam_global_regression_intel_test" )
      	cleanWs(cleanWhenSuccess: true, cleanWhenFailure: true)
        sh 'chmod -R 755 /home/jenkins/cam_output'
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" ==	"cam_global_regression_intel_test" )
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
